// Badge honesty (spec v0.2.29): a flag generated by an assumed vessel
// parameter must name that parameter specifically; a fully-specified charge
// must never render a generic "estimated" badge. In particular the Hamburg
// Port Fee must not read as an estimated charge when only its NOx Tier is
// assumed - the rates, bands, cap, and minimum are verified tariff data.
//
// Badge kinds:
//   estimated_parameter / contract_vs_published  -> unchanged (real estimate)
//   assumed_parameter + parameter name          -> parameter-specific badge
//   fallback_value (least-favourable default)    -> named-basis badge, shown
//                                                   as info, not "est."
import { QualityFlag } from '@port-cost/core';

export interface FlagBadge {
  label: string;
  kind: 'estimated' | 'assumed' | 'caveat' | 'info';
  title?: string;
}

const PARAMETER_BADGES: Record<string, { label: string; title: string }> = {
  engine_tier: {
    label: 'NOx Tier assumed',
    title: 'The NOx Tier is assumed at its worst case (Tier 0) because it was not entered; enter the certified IAPP tier to override. The tariff rates, bands, cap, and minimum on this line are verified data.'
  }
};

export function badgesForFlags(flags: QualityFlag[]): FlagBadge[] {
  const badges: FlagBadge[] = [];
  let hasEstimated = false;
  let hasCaveat = false;
  const infoCount = { n: 0 };
  for (const flag of flags) {
    if (flag.type === 'estimated_parameter') {
      hasEstimated = true;
    } else if (flag.type === 'contract_vs_published') {
      hasCaveat = true;
    } else if (flag.type === 'assumed_parameter') {
      const named = flag.parameter ? PARAMETER_BADGES[flag.parameter] : undefined;
      if (named) {
        badges.push({ label: named.label, kind: 'assumed', title: named.title });
      } else {
        badges.push({
          label: `${flag.parameter ?? 'parameter'} assumed`,
          kind: 'assumed',
          title: flag.description
        });
      }
    } else if (flag.type === 'fallback_value') {
      badges.push({ label: 'default applied', kind: 'info', title: flag.description });
    } else if (flag.type === 'regulatory_notice') {
      // EU regulatory notice (spec v0.2.69): the FuelEU annual-balance
      // disclosure — its own badge so the notice reads as the regulatory
      // disclosure it is, not a generic flag count (badge honesty).
      badges.push({ label: 'FuelEU notice', kind: 'info', title: flag.description });
    } else if (flag.type === 'ets_user_specified_basis') {
      // ETS user-specified basis (spec v0.2.69): the emissions basis and
      // the EUA price are the user's own inputs — named, never a generic
      // estimate badge.
      badges.push({ label: 'ETS user basis', kind: 'assumed', title: flag.description });
    } else {
      infoCount.n += 1;
    }
  }
  if (hasEstimated) {
    badges.unshift({ label: 'est.', kind: 'estimated' });
  }
  if (hasCaveat) {
    badges.push({ label: 'contract rate may differ', kind: 'caveat' });
  }
  if (infoCount.n > 0) {
    badges.push({ label: `${infoCount.n} flag${infoCount.n > 1 ? 's' : ''}`, kind: 'info' });
  }
  return badges;
}
