// Badge-honesty pins (spec v0.2.29): a flag generated by an assumed vessel
// parameter must name that parameter specifically; a fully-specified charge
// must never render a generic "estimated" badge. The Hamburg Port Fee with
// only its NOx Tier assumed must show "NOx Tier assumed", never "est.".
import { badgesForFlags } from './flagBadges';
import { QualityFlag } from '@port-cost/core';

const flag = (type: string, extra: Partial<QualityFlag> = {}): QualityFlag =>
  ({ type, description: 'x', severity: 'info', ...extra } as QualityFlag);

describe('flagBadges (spec v0.2.29 badge honesty)', () => {
  it('an assumed NOx Tier renders a parameter-specific badge, never "est."', () => {
    const badges = badgesForFlags([
      flag('assumed_parameter', { parameter: 'engine_tier', description: 'NOx Tier not entered; worst case (Tier 0) applied' })
    ]);
    expect(badges.some(b => b.label === 'NOx Tier assumed')).toBe(true);
    expect(badges.some(b => b.label === 'est.')).toBe(false);
  });

  it('a fully-specified charge renders no badge at all', () => {
    expect(badgesForFlags([])).toEqual([]);
  });

  it('a real estimated parameter still renders "est."', () => {
    const badges = badgesForFlags([
      flag('estimated_parameter', { description: 'HHLA rate unpublished; anchored to Eurogate 5.1.1' })
    ]);
    expect(badges.some(b => b.label === 'est.')).toBe(true);
  });

  it('estimated and assumed badges coexist on one line without conflating', () => {
    const badges = badgesForFlags([
      flag('estimated_parameter'),
      flag('assumed_parameter', { parameter: 'engine_tier' })
    ]);
    expect(badges.some(b => b.label === 'est.')).toBe(true);
    expect(badges.some(b => b.label === 'NOx Tier assumed')).toBe(true);
  });

  it('the Tier-assumed badge title states that the tariff rates are verified data', () => {
    const badges = badgesForFlags([
      flag('assumed_parameter', { parameter: 'engine_tier', description: 'NOx Tier not entered; worst case (Tier 0) applied' })
    ]);
    const tierBadge = badges.find(b => b.label === 'NOx Tier assumed')!;
    expect(tierBadge.title).toBeDefined();
    expect(tierBadge.title).toContain('verified data');
  });

  it('an assumed tug_count renders a parameter-specific badge carrying the flag description as its title (v0.2.35 health-check pin)', () => {
    const badges = badgesForFlags([
      flag('assumed_parameter', {
        parameter: 'tug_count',
        description: 'Tug requirement not entered; port default of 2 tugs applied; enter the actual requirement to override'
      })
    ]);
    const tugBadge = badges.find(b => b.label === 'tug_count assumed');
    expect(tugBadge).toBeDefined();
    expect(tugBadge!.title).toBe(
      'Tug requirement not entered; port default of 2 tugs applied; enter the actual requirement to override'
    );
    expect(badges.some(b => b.label === 'est.')).toBe(false);
  });
  it('contract-vs-published keeps its caveat badge', () => {
    const badges = badgesForFlags([flag('contract_vs_published')]);
    expect(badges.some(b => b.label === 'contract rate may differ')).toBe(true);
  });

  it('a least-favourable fallback renders a named default badge, not "est."', () => {
    const badges = badgesForFlags([flag('fallback_value', { description: 'Environmental class not supplied; defaulted to E' })]);
    expect(badges.some(b => b.label === 'default applied')).toBe(true);
    expect(badges.some(b => b.label === 'est.')).toBe(false);
  });

});
